name: Deploy toolbox

on:
  push:
    branches:
      - master  # 或者你要触发部署的分支名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 确保与 Nuxt 3 兼容的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Nuxt 3 生成的静态文件默认在 dist 目录下
